### PR TITLE
Add docs generator

### LINKED ISSUE #38: Add api docs generator

### PR DESCRIPTION
**Pull request by JakeRoggenbuck**
fixes #38

### CODE REVIEW

**Comment by JakeRoggenbuck** [comment]
The path to /api/docs is blocked without a token. This needs to be fixed before merge.

**Comment by JakeRoggenbuck** [comment]
Here is what I get when I open the docs route `/api/docs`
image

**Comment by JakeRoggenbuck** [comment]
Here is what it looks like on the server side
image

**Comment by JakeRoggenbuck** [comment]
the route needs a token, because I can access it when I provide one
image

**Comment by JakeRoggenbuck** [comment]
It works!
image

**Review by moltenL — APPROVED** [review]
Reviewed

**Pull request merged**
